### ISSUE TITLE
More symbols

### ISSUE THREAD

**Issue by lunaroyster** [lunaroyster/LaTeX-search#1]
It's simple. Let's add more symbols

**Comment by isa3bel** [comment]
Hi, I added a tax symbol. I am new to open source, so let me know if this was done correctly. I created a PR. Also, how do I test my changes locally on my machine? Thanks!

**Comment by lunaroyster** [comment]
Thanks @isa3bel!

To run the project, take a look at this: https://github.com/lunaroyster/LaTeX-search/blob/master/react-readme.md

**Comment by isa3bel** [comment]
I think I created a PR for a branch called tax. Was it removed?

**Comment by lunaroyster** [comment]
It looked good, so I merged your PR. Here: https://github.com/lunaroyster/LaTeX-search/pull/3 

Again, thanks for contributing!

**Comment by isa3bel** [comment]
are there a list of symbols that still need to be added? I can add some more and create a PR

**Comment by isa3bel** [comment]
also, since you changed master, how do I get the latest on my local machine? if I do git pull it says I have the latest even though I don't since you changed a bit of wording from my PR

**Comment by lunaroyster** [comment]
@isa3bel I updated the first comment to include a list. 

You need to merge the upstream repo. Here are some resources:

https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork

https://help.github.com/en/articles/getting-changes-from-a-remote-repository#fetching-changes-from-a-remote-repository

**Comment by isa3bel** [comment]
git fetch https://github.com/lunaroyster/LaTeX-search master

I used this command but my local was still not updated.

**Comment by lunaroyster** [comment]
try `git pull https://github.com/lunaroyster/LaTeX-search master`.

`fetch` only downloads the changes, while `pull` also merges them

**Comment by isa3bel** [comment]
got it thanks!

So I got the latest changes, committed, and then pushed. Did I push to the forked repo rather than directly to your master? I just pushed, but didn't sent out a PR, since that's unnecessary.

**Comment by lunaroyster** [comment]
It looks like you merged commits from the remote, and pushed to your fork.

**Comment by isa3bel** [comment]
I get these strange errors if I try to run the program on my local machine:

> react-scripts start

sh: react-scripts: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! latexsearch@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the latexsearch@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/isabelbolger/.npm/_logs/2019-10-05T03_34_37_550Z-debug.log


do you know what the error could be?

**Comment by lunaroyster** [comment]
I think you can try prefixing those commands with `npx`? That indicates you're referring to a package locally installed in latex-search (rather than globally installed). Lemme know if this works.
